.gitignore, public/index.html, src/Components/App/App.js, src/Components/Buy/Buy.js, src/Components/Map/Map.js, src/mapbox-accessToken.js
Changes: 
- Took out the leaflet script tag from the index.html
- Map markers are working when being passed from other components
- refactored the Map component to use a function to create the map so that it can be called multiple times if needed.
=> Map component

src/Components/App/App.test.js, src/Components/App/__snapshots__/App.test.js.snap, src/Components/Buy/Buy.test.js, src/Components/Buy/__snapshots__/Buy.test.js.snap, src/Components/Map/Map.test.js, src/Components/Product/Product.test.js, src/Components/Product/__snapshots__/Product.test.js.snap, src/Components/ProductList/ProductList.test.js, src/Components/ProductList/__snapshots__/ProductList.test.js.snap, src/Components/Search/Search.test.js
Changes: 
- add test files to each component
- add snapshot tests for each component
Issues: 
- Map snapshot is not working because of an issue with Leaflet. i will continue to research how to pass. 
- The Search test shows as failing, but that's because both associated files are empty at the moment
=> Add test files and setup snapshot tests

package.json, src/Components/App/App.js, src/Components/Buy/Buy.js, src/Components/Buy/__snapshots__/Buy.test.js.snap, src/Components/Map/Map.js, src/Components/ProductList/ProductList.js, src/Components/Profile/Profile.js
Changes: 
- added history package to dependencies - run npm install after pull
- added history listener on Map component to ensure that the map reloads when the back button is pressed
- figured out how to remove the map to prevent Map initialized error on re-render
=> Map bug seems to be fixed

src/Components/Header/Header.js, src/Components/Header/__snapshots__/Header.test.js.snap, src/styles/_Buy.scss, src/styles/_Header.scss, src/styles/main.scss
I completely restyled the header, looks like this now:
=> Restyle header

src/Components/App/App.js, src/Components/Buy/Buy.js, src/Components/Buy/__snapshots__/Buy.test.js.snap, src/Components/Map/Map.js, src/Components/Search/Search.js, src/styles/_Buy.scss, src/styles/_Map.scss, src/styles/_Productlist.scss, src/styles/_Profile.scss, src/styles/_Search.scss, src/styles/main.scss
changes add basic search functionality
need to fix:
products on user profile,
make search fields required
=> Search func

src/Components/App/App.js
Changes: 
- fixed addUserToStore to a default value until login is ready
=> Fix redux bugs

src/Components/App/App.js, src/helpers/cleaner.js
Closes issue #37 
Changes:
Add a function to cleaner to format phone numbers
issues: 
right now the cleaner function returns phone numbers as a string this can easily be changed if needed
=> Add cleaner func to format phone number

src/Components/App/App.js, src/Components/Message/Message.js, src/actions/index.js, src/reducers/index.js, src/reducers/messageReducer.js, src/styles/_Message.scss, src/styles/main.scss
closes issue #33 
changes: 
addMessage action
messageReducer
message component
issues: 
right now the only message we have is for if a user doesn't add a search location, we'll want to add more messages as we go on
message container is being rendered directly under the header, it could as be rendered off to the side...???
=> Message component

package.json, src/Components/App/App.js, src/Components/Loading/Loading.js, src/Components/Loading/Loading.test.js, src/Components/Loading/__snapshots__/Loading.test.js.snap, src/styles/_Header.scss, src/styles/_Loading.scss, src/styles/main.scss
closes issue #32 
changes:
- add loading component, styled and tested
- minor header css changes
- also added test coverage to package.json
note:
right now app is rendering Loading inside the switch statement, you can see it at "/loading", I'm not sure where/went we want to utilize the Loading component
=> Loading component

src/Components/App/App.js, src/Components/Login/Login.js, src/containers/Login/Login.js, src/styles/_Login.scss, src/styles/main.scss
=> Login page

src/Components/About/About.js, src/Components/App/App.js, src/styles/_About.scss, src/styles/main.scss
Added an about page, still need more content
=> Add about page

src/Components/App/App.js, src/containers/Login/Login.js, src/helpers/cleaner.js, src/thunks/fetchUser.js, src/thunks/loginUser.js
Changes:
- Login container actually logins user now
- add cleaner funcs 
- add thunks for login and getting single user info
=> Add login func

src/components/Header/Header.js, src/components/Header/__snapshots__/Header.test.js.snap, src/styles/_Header.scss
Changes:
Add menu and icon to header so its more user friendly
=> Add menu and icon to header

src/components/AddProductForm/AddProductForm.js, src/components/App/App.js, src/helpers/cleaner.js, src/thunks/fetchUser.js, src/thunks/postItem.js
Changes: 
- setup the AddProductForm component
- setup new thunk for adding item to database
still need to style AddProductForm
=> Add vendor items

src/actions/index.js, src/components/App/App.js, src/components/Buy/Buy.js, src/components/Map/Map.js, src/components/Search/Search.js, src/helpers/cleaner.js, src/reducers/index.js, src/reducers/searchResultsReducer.js, src/thunks/searchVendors.js
=> Search redux

src/actions/index.js, src/components/App/App.js, src/components/Header/Header.js
add sign out functionality to header icon
=> Signout func

src/components/AddProductForm/AddProductForm.js, src/components/Header/__snapshots__/Header.test.js.snap, src/helpers/cleaner.js, src/helpers/cleaner.test.js, src/styles/_AddProductForm.scss, src/styles/_Header.scss, src/styles/_Loading.scss, src/styles/_Login.scss, src/styles/_Map.scss, src/styles/_Message.scss, src/styles/_Productlist.scss, src/styles/_Search.scss, src/styles/main.scss
Changes: 
Add productlist to addProductForm
Change accent color scss variables, yay green!
Add vendorName to user products, so profile page table has vendor column now
updated snapshots and test
=> Productlist

src/components/ProductList/ProductList.js, src/containers/App/App.js, src/containers/App/__snapshots__/App.test.js.snap, src/containers/Header/Header.js, src/containers/Header/__snapshots__/Header.test.js.snap, src/containers/Login/Login.js, src/containers/Map/Map.js, src/containers/Map/__snapshots__/Map.test.js.snap, src/containers/Profile/Profile.js, src/containers/Profile/Profile.test.js, src/containers/Profile/__snapshots__/Profile.test.js.snap, src/helpers/cleaner.js, src/helpers/cleaner.test.js, src/styles/_Header.scss, src/styles/_Profile.scss, src/styles/_Search.scss, src/styles/main.scss
Addresses issues #14, #97
Changes: 
- Change search css colors, edit menu
- Reuse profile for any producer not just signed in user at path /profile/:id
- Add anchor tag to vendor name on map popup link to profile page
- Show custom profile picture if there is one
- Update tests
=> Profile pages

src/containers/Header/Header.js, src/containers/Header/__snapshots__/Header.test.js.snap
changes:
- Add more menu options: sign in, about
=> More menu options

src/containers/AddProductForm/AddProductForm.js, src/containers/AddProductForm/__snapshots__/AddProductForm.test.js.snap, src/containers/Profile/Profile.js, src/containers/Profile/Profile.test.js, src/containers/Profile/__snapshots__/Profile.test.js.snap, src/styles/_Login.scss
Changes: 
- Fix profile picture bug 
- Change add product form link
- Update profile bio
=> Fix minor bugs
